[workspace]
members = [
    "crates/nyx-cli",
    "crates/nyx-compiler",
    "crates/nyx-diagnostic",
    "crates/nyx-lexer",
    "crates/nyx-parser",
    "crates/nyx-source",
    "crates/nyx-token",
]
resolver = "3"

[workspace.dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
thiserror = "2.0.18"
num_enum = "0.7.6"

nyx-diagnostic = { path = "crates/nyx-diagnostic" }
nyx-source = { path = "crates/nyx-source" }
nyx-token = { path = "crates/nyx-token" }
nyx-lexer = { path = "crates/nyx-lexer" }
nyx-parser = { path = "crates/nyx-parser" }
nyx-compiler = { path = "crates/nyx-compiler" }

# Dev deps
insta = "1.48.0"
rstest = "0.26.1"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
